### ISSUE TITLE
Where to get bbb_144p_h264_enc.mp4?

### ISSUE THREAD

**Issue by DCNick3** [DavidBuchanan314/DeCENC#2]
It took me quite some time to figure out that `./testall.sh` demo loops for nothing, as the repo doesn't have the `test_files/bbb_144p_h264_enc.mp4` used in this test.

I also can't seem to find any reference to this filename anywhere besides your repo. Did you create it yourself?

**Comment by DavidBuchanan314** [comment]
oops, they were in my gitignore, should be fixed now
